config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.limit(3).order(created_at: :desc )
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post =Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
    redirect_to @post
  end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <!--  <a class="navbar-brand" href="#">Alex Blog</a> -->
      <%= link_to "Alex Blog", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_disqs.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'bloggingcourses';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @post do |f| %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3 class="titre">A propos </h3>
      <p class="content">Wes Anderson occupy bespoke narwhal, yr single-origin coffee Truffaut semiotics listicle sriracha asymmetrical. Butcher aesthetic PBR vinyl Intelligentsia narwhal wolf ennui four loko readymade asymmetrical hoodie meditation street art High Life. Biodiesel leggings cornhole paleo, plaid iPhone keffiyeh 8-bit kale chips mustache High Life organic heirloom. Helvetica selfies YOLO Bushwick Williamsburg. Sartorial narwhal bitters, normcore tilde hashtag small batch mumblecore deep v pour-over tattooed lomo vinyl Carles. Wes Anderson try-hard distillery banh mi Austin cold-pressed. Narwhal letterpress sriracha next level keytar, Banksy actually +1 Neutra Echo Park food truck XOXO Etsy scenester.

      Tofu Echo Park scenester bicycle rights. Locavore fixie authentic VHS, banh mi post-ironic wayfarers Portland. Yr freegan single-origin coffee cliche actually Thundercats, mlkshk Intelligentsia tofu Helvetica bespoke polaroid. Pinterest Williamsburg banjo, actually literally hashtag Blue Bottle cray raw denim DIY pug quinoa meggings flexitarian cold-pressed. Wayfarers forage iPhone semiotics. Pour-over gluten-free fixie, Thundercats Portland readymade Kickstarter fap XOXO messenger bag. Chillwave tofu single-origin coffee, VHS 3 wolf moon 90's hashtag roof party Williamsburg.</p>
    </div>
    <div class="col-md-4">
      <h3 class="titre">mes derniers articles</h3>
      <div class="content">
        <% @posts.each do |post| %>
          <h3><%= link_to post.title.capitalize.first(24), post %></h3>
          <p class="date"><%= post.created_at.strftime("%d %B %Y") %></p>

          <%= link_to "Effacer", post_path(post), method: :delete, data: { confirm: "Etes vous certain de vouloir effacer ce post ?"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="text-center">
        <p class="date"><%= @post.created_at.strftime("%d %B %Y") %></p>
        <h2><%= @post.title %></h2>
        <hr>
        <p><%= markdown(@post.content) %></p>
        <div id="share_box">
            <p>Share <%= @post.title %></p>
            <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @acordani &mdash; &amp;url=<%= url_for([ @post, { only_path: false } ]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
              <i class="fa fa-twitter"></i>
            </a>
            <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([ @post, { only_path: false } ]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
              <i class="fa fa-facebook"></i>
            </a>
            <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([ @post, { only_path: false } ]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
              <i class="fa fa-google-plus"></i>
            </a>
          </div>
          <hr>
          <%= render 'disqs' %>
        <%= link_to "Editer", edit_post_path(@post) %>
        <%= link_to "Retourner à la liste de tous les posts", posts_path %>
      </div>
    </div>
  </div>
</div>